/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2015-05-22 04:29:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.employees;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class novo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Novo empregado</title>\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"./plugins/bootstrap-3.3.4-dist/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Optional theme -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"./plugins/bootstrap-3.3.4-dist/css/bootstrap-theme.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified JavaScript -->\r\n");
      out.write("<script src=\"./plugins/bootstrap-3.3.4-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".acoes {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tbackground-color: #EFEFEF;\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-group {\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-group.div20 {\r\n");
      out.write("\twidth: 20%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1>Novo empregado</h1>\r\n");
      out.write("\t<form action=\"./employees?logica=salvar\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"txtEmployeeId\" name=\"employeeId\"\r\n");
      out.write("\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employee.employeeId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"acoes\">\r\n");
      out.write("\t\t\t<button type=\"submit\" class=\"btn btn-primary\">Salvar</button>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"txtFirstName\">Primeiro Nome:</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\tid=\"txtFirstName\" name=\"firstName\" class=\"form-control\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"txtLastName\">Ultimo Nome:</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\tid=\"txtLastName\" name=\"lastName\" class=\"form-control\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"txtEmail\">Email:</label> <input type=\"text\" id=\"txtEmail\"\r\n");
      out.write("\t\t\t\tname=\"email\" class=\"form-control\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group div20\">\r\n");
      out.write("\t\t\t<label for=\"txtHireDate\">Admissão:</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\tid=\"txtHireDate\" name=\"hireDate\" class=\"form-control\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"form-group div20\">\r\n");
      out.write("\t\t\t<label for=\"txtJobId\">Job.Id:</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\tid=\"txtJobId\" name=\"jobId\" class=\"form-control\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"form-group div20\">\r\n");
      out.write("\t\t\t<label for=\"txtSalary\">Salário:</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\tid=\"txtSalary\" name=\"salary\" class=\"form-control\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"form-group div20\">\r\n");
      out.write("\t\t\t<label for=\"txtCommissionPct\">Comissão:</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\tid=\"txtCommissionPct\" name=\"commissionPct\" class=\"form-control\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"form-group div20\">\r\n");
      out.write("\t\t\t<label for=\"txtDepartment\">ID do Departamento:</label> <input\r\n");
      out.write("\t\t\t\ttype=\"text\" id=\"txtDepartmentId\" name=\"departmentId\"\r\n");
      out.write("\t\t\t\tclass=\"form-control\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"form-group div20\">\r\n");
      out.write("\t\t\t<label for=\"txtManagerId\">ID do Gerente:</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\tid=\"txtManagerId\" name=\"managerId\" class=\"form-control\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
